name: Comment on PR

on:
  pull_request:
    types: [opened, synchronize]
    branches: ["main"]

  workflow_dispatch:

jobs:
  verify:
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]' }}
    uses: qlik-oss/qlik-cloud-monitoring-app-workflows/.github/workflows/comment_checklist_pr.yml@v0.1.0
    permissions:
      contents: write
      pull-requests: write
    secrets: inherit
