name: Build a draft release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        type: string
  
jobs:
  create-release:
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]' }}
    uses: qlik-oss/qlik-cloud-monitoring-app-workflows/.github/workflows/draft_release_on_main.yml@v0.1.0
    with:
      tag: ${{ inputs.tag }}
    permissions:
      contents: write
    secrets: inherit
