name: Unbuild app

on:
    pull_request:
        types: [opened, synchronize]
        branches: [ "main" ]
        paths:
          - 'assets/**'

    workflow_dispatch:
  
jobs:
    unbuild:
        if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]' }}
        uses: qlik-oss/qlik-cloud-monitoring-app-workflows/.github/workflows/unbuild_app.yml@v0.1.0
        permissions:
          contents: write
        secrets: inherit
